package org.genai.knowledgebase.llm;

/**
 * Data Transfer Object (DTO) for receiving Q&A responses from the Ollama API.
 *
 * <p>
 * Contains the generated answer from the LLM.
 * </p>
 */
public class OllamaResponse {
    /**
     * The answer generated by the LLM based on the user's question and context.
     */
    private String answer;

    // Constructors
    public OllamaResponse() {}
    public OllamaResponse(String answer) {
        this.answer = answer;
    }

    // Getters and setters
    public String getAnswer() { return answer; }
    public void setAnswer(String answer) { this.answer = answer; }
} 