version: '3.8'
services:
  nginx:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    # This tells Docker to connect to the host machine's network
    # so nginx can proxy requests to your backend running on localhost
    extra_hosts:
      - "host.docker.internal:host-gateway"
