version: '3.8'

services:
  frontend-test:
    build:
      context: .
      dockerfile: Dockerfile
    # The new Dockerfile will expose port 3000 for a simple Node.js server
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
    networks:
      - test-network

networks:
  test-network:
    driver: bridge
