# Netlify configuration for a monorepo.
# This file should be in the root of the repository.

# Base build settings
[build]
  # The base directory tells Netlify which sub-project to build.
  # All commands will be run from this directory.
  base = "market-digest-frontend"
  # This is the command to build the frontend.
  command = "npm run build"
  # The publish directory is relative to the base directory.
  publish = "dist"

# Redirects and proxy rules for the API
[[redirects]]
  from = "/api/*"
  to = "${KOYEB_BACKEND_URL}/api/:splat"
  status = 200
  force = true
