services:
  - type: web
    name: market-digest-backend
    env: docker
    plan: free
    region: oregon
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/market-digest-backend-0.0.1-SNAPSHOT.jar
    envVars:
      - key: NEWS_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: PORT
        value: 8080
